### ISSUE TITLE
gradlew on tarkka Javan version suhteen

### ISSUE THREAD

**Issue by simosavonen** [markolenkkeri/voting-backend#2]
Ongelmia aiheutti tuo https://sdkman.io joka asentaa javasta version 11.

./gradlew bootRun kaatui sen myötä virheilmoitukseen, Gradle could not determine Java version from '...'

Google neuvoi ajamaan komennon joka päivittäisi gradlew uuteen versioon, joka tukee java 11.
Tästä seurasi uusia virheilmoituksia, groovy tms. ei ollut enää yhteensopiva gradlew:n kanssa.

Asia selvisi lopulta kun etsi miten asennetaan tuo mainitsemasi Java 8. 
`sudo apt install openjdk-8-jdk`
Ja kunhan päivittää JAVA_HOME muuttujan osoittamaan juuri tuohon versioon, niin gradlew alkoi toimia.

**Comment by simosavonen** [comment]
Piti vain opetella miten sdkman toimii. 
`sdk list java` näytti listan, mistä löytyi myös versio 8.

**Comment by markolenkkeri** [comment]
Jeps, sdkmanista löytyy kaikesta useita versioita, ja jos noita tuoreempia Javan versioita haluaa käyttää, pitää swappailla aikalailla tavaraa applikaatiosta tuoreemmaksi. Groovystä kaikki lähtee, siellä rupeaa vasta versiossa 2.5 ja sitä uudemmissa olemaan kunnon tuki yli JDK 8:n, koska JDK 9 rikkoi niin paljon asioita. Sitten kun Groovyä käytetään sekä Gradlen puolella, että itse Grailsin puolella..  Grails 3.3.x taasen pohjautuu Spring Boot 1.5:een, joka ei ole tuettu JDK 9 tai isommalla versiolla. Käytännössä, jos ihan tuoretta JDK:ta haluaa käyttää, pitäisi swapata Grails 4.0:aan, joka ei vielä ole valmis, eikä sille ole vielä luonnollisesti kaikkia pluginejakaan päivitetty -> spring-security-pohjaiset toteutukset eivät vielä toimi -> tämäkään sovellus ei Grails 4:ssä vielä toimi. Ehkä kohta sitten =)
